apiVersion: v1
kind: Pod
metadata:
  name: dapi-keys-permission-pod
  labels:
    region: r1
    zone: z11
    rack: a111
  annotations:
    build: one
    builder: qe-one
spec:
  containers:
    - name: client-container
      image: docker.io/ocpqe/hello-pod:latest
      securityContext:
        privileged: false
      volumeMounts:
        - name: podinfo
          mountPath: /var/tmp/podinfo
          readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
            mode: 0400
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
            mode: 0501
          - path: "name"
            fieldRef:
              fieldPath: metadata.name
            mode: 0511
          - path: "namespace"
            fieldRef:
              fieldPath: metadata.namespace
            mode: 0100
